version: "3.7"

services:
  rabbitmq:
    image: juanmartinez/rabbitmq:3.8.3
    container_name: rabbitmq
    hostname: rabbitmq
    env_file:
    - rabbitmq.env
    ports:
    - "15672:15672"

  hoster:
    image: juanmartinez/docker-hoster
    container_name: hadoop_hoster
    hostname: hadoop_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts