version: "3.7"

services:

  zookeeper-server:
    image: juanmartinez/zookeeper:3.4.14
    container_name: zookeeper-server
    hostname: zookeeper-server
    env_file:
      - ./zookeeper.env

  namenode:
    image: juanmartinez/hadoop:2.7.7
    container_name: namenode
    hostname: namenode
    ports:
      - "50070:50070"
    volumes:
      - ./data/namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=local
    env_file:
      - ./hadoop.env

  datanode:
    image: juanmartinez/hadoop:2.7.7
    container_name: datanode
    hostname: datanode
    volumes:
      - ./data/datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    env_file:
      - ./hadoop.env

  accumulo:
    image: juanmartinez/accumulo:1.9.3
    container_name: accumulo
    hostname: accumulo
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    depends_on:
      - namenode
    env_file:
      - ./accumulo.env

  hoster:
    image: juanmartinez/docker-hoster
    container_name: hadoop_hoster
    hostname: hadoop_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
