  
version: "3.8"

services:
  hue:
    image: juanmartinez/hue:4.7.1
    container_name: hue
    hostname: hue
    env_file:
    - hue.env

  hoster:
    image: juanmartinez/docker-hoster
    container_name: hadoop_hoster
    hostname: hue_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts