version: "3.7"

services:
  zookeeper-server:
    image: juanmartinez/zookeeper:3.4.14
    container_name: zookeeper-server
    hostname: zookeeper-server
    env_file:
    - zookeeper.env
  kafka-broker:
    image: juanmartinez/kafka:2.3.1
    container_name: kafka-broker
    hostname: kafka-broker
    env_file:
    - kafka.env

  hoster:
    image: juanmartinez/docker-hoster
    container_name: hadoop_hoster
    hostname: hadoop_hoster
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
